"""I=Rotor("EKMFLGDQVZNTOWYHXUSPAIBRC","Q")
    II=Rotor("AJDKSIRUXBLHWTMCQGZNPYFVOE","E")
    III=Rotor("BDFHJLCPRTXVZNYEIWGAKMUSQO","V")
    IV=Rotor("ESOVPZJAYQUIRHXLNFTGKDCMWB","J")
    V=Rotor("VZBRGITYUPSDNHLXAWMJQOFECK","Z")"""
